#!/usr/bin/env node
// Generates a .env file with strong random secrets for docker compose.
// Usage: node scripts/setup-env.mjs [--public-url https://poker.example.org] [--lan http://192.168.1.20:8080] [--force]
import { randomBytes } from 'node:crypto';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';

const args = process.argv.slice(2);
const flag = (name) => {
  const i = args.indexOf(name);
  return i === -1 ? null : (args[i + 1] ?? null);
};
const force = args.includes('--force');
if (existsSync('.env') && !force) {
  console.error('.env already exists. Re-run with --force to overwrite (this rotates every secret).');
  process.exit(1);
}

const hex = (bytes) => randomBytes(bytes).toString('hex');
const password = () => randomBytes(18).toString('base64url');
const lan = flag('--lan');
const publicUrl = flag('--public-url') ?? lan ?? 'http://localhost:8080';
const adminPassword = password();
const metricsToken = hex(24);

const lines = [
  '# Generated by scripts/setup-env.mjs — keep this file secret and backed up.',
  '# Losing SEED_ENCRYPTION_KEY means seeds of unfinished tournaments cannot be revealed for audit.',
  `PUBLIC_BASE_URL=${publicUrl}`,
  `POSTGRES_PASSWORD=${password()}`,
  `SEED_ENCRYPTION_KEY=${hex(32)}`,
  'BOOTSTRAP_ADMIN_USERNAME=admin',
  `BOOTSTRAP_ADMIN_PASSWORD=${adminPassword}`,
  `METRICS_TOKEN=${metricsToken}`,
  `GRAFANA_ADMIN_PASSWORD=${password()}`,
  `COOKIE_SECURE=${lan || publicUrl.startsWith('http://') ? 'false' : 'true'}`,
  `ALLOW_INSECURE_LAN_HTTP=${lan || publicUrl.startsWith('http://') ? 'true' : 'false'}`,
  'APP_PORT=8080',
  'BACKUP_RETENTION_DAYS=14',
  '',
];
writeFileSync('.env', lines.join('\n'), { mode: 0o600 });
// Prometheus reads the scrape token from a file (it does not expand environment variables).
mkdirSync('.secrets', { recursive: true, mode: 0o700 });
writeFileSync('.secrets/metrics_token', metricsToken, { mode: 0o644 });
console.log('Wrote .env');
console.log(`Admin login:   admin / ${adminPassword}`);
console.log('Change it after first login (Admin → Users). This password is shown only once.');
